### ISSUE TITLE
Can't continue after signing up

### ISSUE THREAD

**Issue by florian-lefebvre** [joshcawthorne/work-from#1]
Hi @joshcawthorne, that's an awesome project!
I wanted to try it out and encountered an issue.
After clicking on the magic link to sign up, I get a form to give my name. That's fine but then the animation runs and I only have an empty box at the center of the screen.
![image](https://user-images.githubusercontent.com/69633530/128842020-24c4a7ab-903a-4b4c-8967-68f755ed5261.png)
Here are what I got on the devtools:
![image](https://user-images.githubusercontent.com/69633530/128842152-e3e29e41-3a3d-43c8-9d2c-868f6a264286.png)
![image](https://user-images.githubusercontent.com/69633530/128842282-71e5b0e7-5aee-46da-9ad1-d1c5bc4bc34e.png)
I'm using Mozilla Firefox developer edition on Windows 10.

**Comment by Starboy-Sharma** [comment]
I am also facing the same issue in Firefox browser. But after some time when I load app again. It takes me to the login page.

**Comment by joshcawthorne** [comment]
Hey @florian-lefebvre @Starboy-Sharma, looks like something in Firefox might not be triggering the animation. I'll take a look!

**Comment by joshcawthorne** [comment]
Think I've resolved this in the latest commit! Issue was the animation relying on the css property `fit-content`, which Firefox doesn't use 😅

**Comment by florian-lefebvre** [comment]
It works @joshcawthorne 👍
